In [236]:
# Lösa systemet av ekvationer Ax = b med Gausselimination
# med pivoting

import numpy as np
import sys

FUNKTIONER

In [22]:
# utbytta rader
def utbyta_rader(m, a, b):
    """
    Byter plats på raderna a och b i matrisen m
    """
    temp = m[a].copy()
    m[a] = m[b]
    m[b] = temp
    return m

In [23]:
# moltiplikation av en rad med ett tal
def mult_rad(m, n, a, b):
    """
    Multiplicerar raden a i matrisen m med talet b
    """
    m[a] = m[a] * b
    n[a] = n[a] * b
    return m, n

In [24]:
# ersätt en rad i matrisen med den som erhålls genom att lägga till en multipel av en annan rad.
def ersatt_rad(m, n, a, b, c):
    """
    Ersätter raden a i matrisen m med raden b multiplicerad med talet c
    """
    m[a] = m[a]*c + m[b]
    n[a] = n[a]*c + n[b]
    return m, n

In [3]:
# printa ut systemet av ekvationer
def printa_ekvationer(a, b):
    alfabetet = "abcdefghijklmnopqrstuvwxyz"
    for i in range(len(a)):
        print(" + ".join([f"{a[i,j]}{alfabetet[j]}" for j in range(len(a))]), "=", b[i])

In [ ]:
# printa ut om en matris är skalär
def printa_skalar(a):
    i, j = a.shape
    count = i * j
    check = 1
    for r in range(1, i):
        for c in range(0, j-1):
            if a[r][c] == 0:
                check += 1
            else:
                check -= 1
    if check == count / 3:
        print("Matrisen är skalär")
        return True
    else:
        print("Matrisen är inte skalär")
        return False


In [27]:
# ordna matrisen på raderna
def ordna_matris(a, b):
    """
    Ordna matriser a och b på första värde i raderna   
    """
    
    for i in range(len(a)-1):
        for j in range(1, len(a)):
            if a[i, j-1] < a[i+1, j]:
                utbyta_rader(a, i, i+1)
                utbyta_rader(b, i, i+1)

    return a, b
# mettere la riga con valore zero in fondo

In [35]:
def ordna_matris2(a, b):
    """
    Ordna matriser a och b på första värde i raderna   
    """
    n = len(a)
    for i in range(n):
        if a[i, 0] == 0:
            utbyta_rader(a, i, n-1)
            utbyta_rader(b, i, n-1)

    return a, b

In [ ]:
# beräkna skalär matris
def berakna_skalar(a, b):
    """
    Beräkna skalär matris
    """
    for j in range(1, len(a)):
        for i in range(j, len(a)):
            if a[i, j-1] != 0:
                k = -(a[i-1, j-1] / a[i, j-1])
                #print(k)
                ersatt_rad(a, b, i, i-1, k)
    
    return a, b

In [222]:
# Applying Gauss Elimination
def gauss_elimination(a, b):
    n = len(b)
    j = 0
    #print('n:', n)
    while j < 2:
        #print('j:', j)
        for i in range(j, n-1):
            #print('i:', i)
            k = (a[i+1, j] / a[j, j])
            a[i+1] = k * a[j] - a[i+1]
            b[i+1] = k * b[j] - b[i+1]
            #printa_ekvationer(a, b)
        #print('\n')
        j += 1
    
    return a, b

In [228]:
def solve_gauss(a, b):
    n=len(b)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        print('i+1:n:', f'{i+1}:{n}')
        print('a[i, i+1:n]:', a[i, i+1:n])
        print('x[i+1:n]:', x[i+1:n])
        x[i] = (b[i] - np.dot(a[i, i+1:n], x[i+1:n]))/a[i, i]
    #x[n-1]=(b[n-1]                                      )/a[n-1, n-1]
    #x[n-2]=(b[n-2]-a[n-2, n-1]*x[n-1]                   )/a[n-2, n-2]
    #x[n-3]=(b[n-3]-a[n-3, n-2]*x[n-2]-a[n-2, n-1]*x[n-1])/a[n-3, n-3]
    
    return x

CODEN

In [237]:
a = np.array([[1, 4], 
              [0, 5],], dtype=float)

b = np.array([5, 7], dtype=float)
ordna_matris2(a, b)
#berakna_skalar(a, b)
printa_ekvationer(a, b)
print('\n')
gauss_elimination(a, b)
print(solve_gauss(a, b))


1.0a + 4.0b = 5.0
0.0a + 5.0b = 7.0


i+1:n: 2:2
a[i, i+1:n]: []
x[i+1:n]: []
i+1:n: 1:2
a[i, i+1:n]: [4.]
x[i+1:n]: [1.4]
[-0.6  1.4]


In [ ]:
gauss_elimination(a, b)

In [107]:
a = a[1:, 1:]
b = b[1:]
gauss_elimination(a, b)

7.0a + 6.0b = 8.0
0.0a + 5.0b = 5.0




(array([[7., 6.],
        [0., 5.]]),
 array([8., 5.]))

In [103]:
for i in range(n):
    a, b = gauss_elimination(a[n:,n:], b[n:])

In [104]:
printa_ekvationer(a, b)

In [97]:
a2 = a[1:,1:]
b2 = b[1:]
print(a2)
print(b2)

[[ 7.  6.]
 [14.  7.]]
[ 8. 11.]


In [98]:
gauss(a2, b2)

7.0a + 6.0b = 8.0
0.0a + 5.0b = 5.0




(array([[7., 6.],
        [0., 5.]]),
 array([8., 5.]))

In [44]:
ordna_matris2(a, b)
printa_ekvationer(a, b)

1.0a + 4.0b + 4.0c = 5.0
3.0a + 5.0b + 6.0c = 7.0
4.0a + 2.0b + 9.0c = 9.0


In [30]:
# Back Substitution
x = np.zeros(n)
x[n-1] = a[n-2][n-1]/a[n-1][n-1]

for i in range(n-2,-1,-1):
    x[i] = a[i][n]
    
    for j in range(i+1,n):
        x[i] = x[i] - a[i][j]*x[j]
    
    x[i] = x[i]/a[i][i]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [239]:
for i in range(1, len(a)):
    if a[i, 0] != 0:
        k = -(a[i-1, 0] / a[i, 0])
        print(k)
        ersatt_rad(a, b, i, i-1, k)
        ordna_matris(a, b)
        printa_ekvationer(a, b)
#printa_ekvationer(a, b)


-0.0
0.0a + 2.0b + 6.0c = 3.0
0.0a + 2.0b + 6.0c = 3.0
0.0a + 4.0b + 4.0c = 2.666666666666667


In [ ]:
k = -(a[0][0] / a[1][0])
print(k)

In [ ]:
print(a)

In [ ]:
a = np.array([[2, 1, -3], 
              [-1, 3, 2], 
              [3, 1, -3]], dtype=float)

b = np.array([-1, 12, 0], dtype=float)
printa_ekvationer(a, b)



In [ ]:
k = -(a[0][0] / a[1][0])
print(k)
a[1] = a[1] * k + a[0]
printa_ekvationer(a, b)

In [ ]:
k = -(a[0][0] / a[2][0])
print(k)
a[2] = a[2] * k + a[0]
printa_ekvationer(a, b)

In [ ]:
k = -(a[1][1] / a[2][1])
print(k)
a[2] = a[2] * k + a[1]
printa_ekvationer(a, b)

In [ ]:

print(a)

# utbytta rader
print(utbyta_rader(a, 1, 2))

# moltiplikation av en rad med ett tal
print(mult_rad(a, 0, 2))

# ersätt en rad i matrisen med den som erhålls genom att lägga till en multipel av en annan rad.
print(ersatt_rad(a, 1, 0, 2))