https://www.youtube.com/watch?v=t4bWsoWEVP4

In [1]:
import numpy as np

In [28]:
# per creare un array numpy è semplice basta usare il metodo array() e passare una lista o una turpla
arr_1d = np.array([1, 2, 3, 4, 5])

arr_2d = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(arr_1d)
print()
print(arr_2d)



[1 2 3 4 5]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
# numero di dimensioni
arr_1d.ndim

1

In [5]:
# numero di elementi nell'array
arr_1d.size

5

In [13]:
# dimensione della matrice
arr_1d.shape

(5,)

In [6]:
arr_1d.min()

1

In [7]:
arr_1d.max()

5

In [8]:
arr_1d.sum()

15

In [11]:
# funzione simile a range() di python che restituisce un np array dove l'ultimo valore è escluso
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
# funzione linspace restituisce un array di n numeri equidistanti un certo intervallo includendo l'ultimo valore del range
# di default vengono restituiti volori come float()
np.linspace(0, 10, 5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
# muoversi i una matrice
# usare le [] con all'interno l'indice di riga e di colonna separata da una virgola

# un valore
arr_2d[0,0]

# una riga intera
arr_2d[0, :]  # oppure arr_2d[0]

# una intera colonna
arr_2d[:, 0]

array([1, 5, 9])

In [19]:
# array di soli zeri
np.zeros(2)         # una dimensione
np.zeros((2, 2))    # una matrice. La dimensione deve essere inserita con una tupla

array([[0., 0.],
       [0., 0.]])

In [20]:
# array o matrice di uno
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [22]:
# arrey o matrice di numeri random
np.random.random(2)
np.random.random((2, 2))

array([[0.84931644, 0.88826119],
       [0.99661158, 0.39050773]])

In [23]:
# matrice identità
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# CAMBIARE LE DIMENSIONI DI UNA MATRICE
# Reshape

print(arr_2d, arr_2d.shape)
print()
arr_2d_res = arr_2d.reshape(4, 3)
print(arr_2d_res, arr_2d_res.shape)
print()

In [30]:
# FILTRARE I DATI CON IL BOLEAN FILTRERING

arr_1d < 3

# se vogliamo che vengano restituiti i valori rispondenti alla condizioni occorre scrivere
arr_1d[arr_1d < 3]

array([1, 2])

In [31]:
# Creare un filtro customizzato con il metodo where()
np.where(
    arr_2d < 4,     # condizione
    1,              # True
    0               # False
    )

array([[1, 1, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [2]:
# confronto tra python e numpy

A = np.random.rand(1000, 1000)
a = A.tolist()

In [11]:
%%time
total = 0
for row in a:
    for n in row:
        total += n
round(total, 2)

CPU times: user 147 ms, sys: 510 µs, total: 147 ms
Wall time: 173 ms


499948.42

In [8]:
%%time
round(np.sum(A), 2)

CPU times: user 0 ns, sys: 2.7 ms, total: 2.7 ms
Wall time: 2.91 ms


499948.42

In [18]:
# ALGEBRA LINEARE
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# prodotto tra i vettori. Il risultato è un vettore della stessa dimensione i cui valori sono moltiplicati tra loro
print(a*b)


# prodotto scalare
print(np.dot(a, b))

[ 4 10 18]
32


In [25]:
# prodotto matriciale

m1 = np.array([
    [1, 2, 3], 
    [5, 6, 7],
    [9, 10, 11]
])

m2 = np.array([
    [5, 6, 7], 
    [1, 2, 3],
    [9, 10, 11]
])

print(np.dot(m1, m2))
m1 @ m2

[[ 34  40  46]
 [ 94 112 130]
 [154 184 214]]


array([[ 34,  40,  46],
       [ 94, 112, 130],
       [154, 184, 214]])